version: '3'

services:
  plex-server:
    image: plexinc/pms-docker
    volumes:
    - ./data/database:/config
    - ./data/transcode:/transcode
    - ./data/media:/data
    environment:
      PLEX_CLAIM: ${PLEX_CLAIM}
      ADVERTISE_IP: ${ADVERTISE_IP}
    ports:
    - 32400:32400
