version: '3'

services:
  plex-server:
    image: plexinc/pms-docker:1.15.4.994-107756f7e
    restart: always
    volumes:
      - ./data/database:/config
      - ./data/transcode:/transcode
      - ./data/media:/data
    environment:
      PLEX_CLAIM: ${PLEX_CLAIM}
      ADVERTISE_IP: ${ADVERTISE_IP}
      TZ: ${TZ}
    network_mode: host
    ports:
      - 32400:32400
